server:
  port: 9001

spring:
  application:
    name: department-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3606/spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect